<div class="container row">
  <form class="col-lg-4 col-lg-offset-4">
    <div class="form-group">
      <label for="exampleInputEmail1">Adresse e-mail</label>
      <input type="email" class="form-control" id="exampleInputEmail1" placeholder="E-mail">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Login (pseudo)</label>
      <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Login">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Mot de passe</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Mot de passe">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Confirmer le mot de passe</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirmation mot de passe">
    </div>
    <select class="selectpicker" name="sujet" id="formulaireHow">

      <option value>Genre</option>

      <option value="bonjour">Par internet</option>

      <option value="devis">Par la presse</option>

      <option value="wut">Le coeur a ses raison, enfin vous comprenez</option>

    </select>
    <div class="checkbox">
      <label>
        <input type="checkbox"> Se souvenir de moi
      </label>
    </div>
    <button type="" class="btn btn-default">Entrer</button>
  </form>
</div>