<div class="container row">
  <div style="background-color:red"><?=$errorEmail?></div>
  <div style="background-color:red"><?=$errorLogin?></div>
  <div style="background-color:red"><?=$errorPwd?></div>
  <form method="POST" class="col-lg-4 col-lg-offset-4">
    <div class="form-group">
      <label for="exampleInputEmail1">Adresse e-mail</label>
      <input type="email" class="form-control" id="InputEmail" name="email"  placeholder="E-mail">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Login (pseudo)</label>
      <input type="login" class="form-control" id="InputLogin" name="login" placeholder="Login">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Mot de passe</label>
      <input type="password" class="form-control" id="InputPassword1" name="pwd1" placeholder="Mot de passe">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Confirmer le mot de passe</label>
      <input type="password" class="form-control" id="InputPassword2" name="pwd2" placeholder="Confirmation mot de passe">
    </div>

    <div class="form-group">
      <select class="form-control" name="gender" id="formulaireHow">

        <option value>Genre</option>

        <option value="homme">Homme</option>

        <option value="femme">Femme</option>

        <option value="deux">Moit' moit'</option>

      </select>
    </div>
    <button type="" class="btn btn-default">S'enregistrer</button>
  </form>
</div>